### ISSUE TITLE
Several problems with your plugin

### ISSUE THREAD

**Issue by Acenox** [SquareCodeFX/AntiReachV6#1]
Hello,
I have several problems with your plugin.

Error 1: https://pastebin.com/zwa0KPYm -> As soon as a player joins I have this error.
Error2: https://pastebin.com/594WJ7ne -> This spam in my console, I have this error in PvP.

Then, if I want to use my own execution commands, it does not work, there are 29 verbose alerts, and that does not want to execute my command for the 30th alert. However, the command works well when I execute it or when I execute it from the console.

Thank you for correcting this, because the problem outside of this is exellent and it's the only bugs I could find!

Spigot version: 1.8.8 (latest)
AntiReach Version: 6.0-BETA
ProtocolLibs: 4.4.0
ViaVersion: Yes

Best regards,

**Comment by SquareCodeFX** [comment]
We are really very sorry, but unfortunately it is not possible for us to reconstruct the problem. The problems they pointed out should not happen. The automatic command that is executed when the level is reached is executed by the console. Note that you did not add a "/" in the command line. Creating Json Configs also works fine. There are no "{" errors. These are set correctly by the Json layout (4). 

Does your user running your server have enough permissions to create files? 
Can he read or edit files? Can the plugin you want to kick about, 
also execute the command in the console?

Yours sincerely,

SquareCode / Felix M.

**Comment by Acenox** [comment]
Hello,
Indeed it seems to be a problem of writing, except that I am on a dedicated machine, and your file even if I put it back in access 777 it is back in access 644.

I made you a video here: https://youtu.be/V0gkLz9RxiQ

and as you can see in the video, there is no kick done with the default config (probably because of the permission error I get).

Ps: I do not have this problem with other plugins.

Thanks you for your help.

Best regards,

**Comment by Acenox** [comment]
Hello,
Indeed it seems to be a problem of writing, except that I am on a dedicated machine, and your file even if I put it back in access 777 it is back in access 644.

I made you a video here: https://youtu.be/wb1kERuWsnA

and as you can see in the video, there is no kick done with the default config (probably because of the permission error I get).

Ps: I do not have this problem with other plugins.

Thanks you for your help.

Best regards,

**Comment by Acenox** [comment]
Hello, 

I just tested the latest version and it corrects the problem! Thank you :)

Best regards,

**Comment by SquareCodeFX** [comment]
_I'm glad I could help you._ 

> Best regards, 
> 
> ~ SquareCode Felix M.
